name: first

on: [push]

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@v4
      - name: Step Two
        run: env | sort
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Step One
        uses: actions/checkout@v4
      - name: Step Two
        run: "Get-ChildItem Env: | Sort-Object Name"

  job3:
    name: Third Job
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo Job 3 after job 1 and job 2

    
  
